apiVersion: v1
kind: Service
metadata:
  name: stream-source-client01
  labels:
    run: stream-source-client01
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: clients-endpoint
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: stream-target
  selector:
    run: stream-source-client01
