apiVersion: v1
kind: Service
metadata:
  name: vyos
  labels:
    run: vyos
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: vyos-80
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: vyos-1935
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: vyos-iperf
  selector:
    run: vyos
