apiVersion: v1
kind: Service
metadata:
  name: stream-cache-client01
  labels:
    run: stream-cache-client01
spec:
  clusterIP: 10.201.100.50
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: stream-cache-client01
