apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stream-cache-client01
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        cni: "calico"
      labels:
        run: stream-cache-client01
    spec:
      containers:
      - name: nginx-cache
        image: michalskalski/docker-nginx-rtmp:frontend
        env:
        - name: HLS_STREAM_SOURCE
          value: http://___CORE_ENDPOINT___
        ports:
        - containerPort: 80
